### ISSUE TITLE
Mylar template : logs errors linked with PIL library

### ISSUE THREAD

**Issue by Tchiimy** [novaspirit/pi-hosted#358]
Hello,

I'm using a RPi4 (with the Raspberry Pi OS 32bits) and I wanted to give a try at your Mylar template on portainer.

After running the container (no changes on the original parameters), I can't access the web interface of Mylar at the address : http://<RPi IP adress>:8090 so I tchecked the logs and found this : 

```
ImportError: cannot import name '_imaging' from 'PIL' (/usr/lib/python3.9/site-packages/PIL/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/app/mylar3/Mylar.py", line 27, in <module>

    import mylar

  File "/app/mylar3/mylar/__init__.py", line 43, in <module>

    from mylar import logger, versioncheckit, rsscheckit, searchit, weeklypullit, PostProcessor, updater, helpers

  File "/app/mylar3/mylar/logger.py", line 24, in <module>

    from mylar import helpers

  File "/app/mylar3/mylar/helpers.py", line 43, in <module>

    from mylar import db, sabnzbd, nzbget, process, getcomics, getimage

  File "/app/mylar3/mylar/getimage.py", line 28, in <module>

    logger.warn('[WARNING] PIL is not available - it\'s used to resize images for notifications, and other things.')

NameError: name 'logger' is not defined

Traceback (most recent call last):

  File "/app/mylar3/mylar/getimage.py", line 23, in <module>

    from PIL import Image

  File "/usr/lib/python3.9/site-packages/PIL/Image.py", line 100, in <module>

    from . import _imaging as core

ImportError: cannot import name '_imaging' from 'PIL' (/usr/lib/python3.9/site-packages/PIL/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/app/mylar3/Mylar.py", line 27, in <module>

    import mylar

  File "/app/mylar3/mylar/__init__.py", line 43, in <module>

    from mylar import logger, versioncheckit, rsscheckit, searchit, weeklypullit, PostProcessor, updater, helpers

  File "/app/mylar3/mylar/logger.py", line 24, in <module>

    from mylar import helpers

  File "/app/mylar3/mylar/helpers.py", line 43, in <module>

    from mylar import db, sabnzbd, nzbget, process, getcomics, getimage

  File "/app/mylar3/mylar/getimage.py", line 28, in <module>

    logger.warn('[WARNING] PIL is not available - it\'s used to resize images for notifications, and other things.')

NameError: name 'logger' is not defined

Traceback (most recent call last):

  File "/app/mylar3/mylar/getimage.py", line 23, in <module>

    from PIL import Image

  File "/usr/lib/python3.9/site-packages/PIL/Image.py", line 100, in <module>

    from . import _imaging as core

ImportError: cannot import name '_imaging' from 'PIL' (/usr/lib/python3.9/site-packages/PIL/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/app/mylar3/Mylar.py", line 27, in <module>

    import mylar

  File "/app/mylar3/mylar/__init__.py", line 43, in <module>

    from mylar import logger, versioncheckit, rsscheckit, searchit, weeklypullit, PostProcessor, updater, helpers

  File "/app/mylar3/mylar/logger.py", line 24, in <module>

    from mylar import helpers

  File "/app/mylar3/mylar/helpers.py", line 43, in <module>

    from mylar import db, sabnzbd, nzbget, process, getcomics, getimage

  File "/app/mylar3/mylar/getimage.py", line 28, in <module>

    logger.warn('[WARNING] PIL is not available - it\'s used to resize images for notifications, and other things.')

NameError: name 'logger' is not defined

Traceback (most recent call last):

  File "/app/mylar3/mylar/getimage.py", line 23, in <module>

    from PIL import Image

  File "/usr/lib/python3.9/site-packages/PIL/Image.py", line 100, in <module>

    from . import _imaging as core

ImportError: cannot import name '_imaging' from 'PIL' (/usr/lib/python3.9/site-packages/PIL/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/app/mylar3/Mylar.py", line 27, in <module>

    import mylar

  File "/app/mylar3/mylar/__init__.py", line 43, in <module>

    from mylar import logger, versioncheckit, rsscheckit, searchit, weeklypullit, PostProcessor, updater, helpers

  File "/app/mylar3/mylar/logger.py", line 24, in <module>

    from mylar import helpers

  File "/app/mylar3/mylar/helpers.py", line 43, in <module>

    from mylar import db, sabnzbd, nzbget, process, getcomics, getimage

  File "/app/mylar3/mylar/getimage.py", line 28, in <module>

    logger.warn('[WARNING] PIL is not available - it\'s used to resize images for notifications, and other things.')

NameError: name 'logger' is not defined

Traceback (most recent call last):

  File "/app/mylar3/mylar/getimage.py", line 23, in <module>

    from PIL import Image

  File "/usr/lib/python3.9/site-packages/PIL/Image.py", line 100, in <module>

    from . import _imaging as core

ImportError: cannot import name '_imaging' from 'PIL' (/usr/lib/python3.9/site-packages/PIL/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/app/mylar3/Mylar.py", line 27, in <module>

    import mylar

  File "/app/mylar3/mylar/__init__.py", line 43, in <module>

    from mylar import logger, versioncheckit, rsscheckit, searchit, weeklypullit, PostProcessor, updater, helpers

  File "/app/mylar3/mylar/logger.py", line 24, in <module>

    from mylar import helpers

  File "/app/mylar3/mylar/helpers.py", line 43, in <module>

    from mylar import db, sabnzbd, nzbget, process, getcomics, getimage

  File "/app/mylar3/mylar/getimage.py", line 28, in <module>

    logger.warn('[WARNING] PIL is not available - it\'s used to resize images for notifications, and other things.')

NameError: name 'logger' is not defined
```

I wanted to know if anybody was in the same situation or found a way to solve this problem ?

**Comment by Tchiimy** [comment]
Okay I've talked with LinuxServer.io they should update the image soon to solve this problem. Feel free to relauch the feed if the problem is back again.
