### ISSUE TITLE
WireGuard container is not deploying correctly

### ISSUE THREAD

**Issue by valyrian84** [novaspirit/pi-hosted#425]
I am using the App Template to deploy WG-Easy.

But I am getting this error - 
_2023-02-19T16:41:57.423Z Server Listening on http://0.0.0.0:51821
2023-02-19T16:41:57.427Z WireGuard Loading configuration...
2023-02-19T16:41:57.431Z WireGuard Configuration loaded.
2023-02-19T16:41:57.431Z WireGuard Config saving...
2023-02-19T16:41:57.435Z WireGuard Config saved.
$ wg-quick down wg0
$ wg-quick up wg0
Error: Command failed: wg-quick up wg0
[#] 
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 192.168.254.0/24/24 dev wg0
Error: inet prefix is expected rather than "192.168.254.0/24/24".
[#] ip link delete dev wg0
    at ChildProcess.exithandler (child_process.js:383:12)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1058:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:400:28)
    at Pipe.<anonymous> (net.js:686:12) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'wg-quick up wg0'_

The ports show up for a second in my container view and then they disappear. No response while trying to access the container locally on either of the ports.

Did anyone face this issue?

**Comment by valyrian84** [comment]
This issue is resolved.
